### ISSUE TITLE
Recall metric implementation

### ISSUE THREAD

**Issue by vmanisha** [NTMC-Community/MatchZoo#720]
- [ Yes] I checked to make sure that this is not a duplicate issue
- [ Yes] I'm submitting the request to the correct repository (for model requests, see [here](https://github.com/NTMC-Community/awaresome-neural-models-for-semantic-match))

### Is your feature request related to a problem? Please describe.
Recall metrics are required for certain type of experiments. 

### Describe the solution you'd like
I was hoping to submit my small implementation as a pull request. What is the best branch to do that? Or should i create a new branch entirely. This will be my first pull request, so I would like as much critical feedback as possible.

**Comment by uduse** [comment]
@vmanisha I agree that recall is a commonly used metric and will be a nice addition to matchzoo. Also, the change you're proposing is rather independent: you only need to add one file under `matchzoo/metrics` and one test under `tests/unit_test/test_metrics.py` so it's a nice feature to PR for beginners.

We have a general contribution guide [here](https://github.com/NTMC-Community/MatchZoo/blob/master/CONTRIBUTING.md) for contributors and you should read that thoroughly. The process might be overwhelming at first since this is your first PR, but no worries, we will help you along the way. You are welcomed to add additional questions in this issue, or chat with us on [gitter](https://gitter.im/NTMC-Community/community?source=orgpage).

In terms of your specific question:

> What is the best branch to do that? 
Your own branch named `feature/add-recall-metric` or something.

**Comment by smenon8** [comment]
Would love to take a stab at this..
