### ISSUE TITLE
AttributeError: 'RankCrossEntropyLoss' object has no attribute '__name__' for Keras model save

### ISSUE THREAD

**Issue by cmacdonald** [NTMC-Community/MatchZoo#753]
### Describe the bug
I wanted to try to save the Keras "backend" model. But `model.backend.save("dssm.keras.model.h5")` didnt work:

AttributeError: 'RankCrossEntropyLoss' object has no attribute '__name__'

### To Reproduce
See gist at https://gist.github.com/cmacdonald/8d86d433c3ca154f746b9864cc2b91de

### Describe your attempts
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this is not a duplicate issue

**Comment by uduse** [comment]
I confirmed it's a bug. On the keras side, using a customized loss only requires the loss to be callable but saving it requires its `__name__` field (the keras dev was being careless, assuming all callables are functions), which matchzoo losses don't have since matchzoo losses are callable class instances instead of functions or methods. Matchzoo losses are class instances instead of fixed functions because their behavior depends on specific parameters (e.g. `num_neg`). As a result, in order for keras to serialize a matchzoo loss, you have to manually wrap the loss instance around a method in the global scope, so the loss is retrievable by its mere name.

We may provide a workaround internally later, but here's a band-aid fix:
`
loss = mz.losses.RankCrossEntropyLoss(num_neg=4)
loss.__name__ = 'my_loss'
ranking_task = mz.tasks.Ranking(loss)
# ......
model.backend.save("dssm.keras.model.h5")
# ......
keras.models.load_model("dssm.keras.model.h5", custom_objects={'my_loss': loss})
`

**Comment by cmacdonald** [comment]
Thanks. I confirm that the band-aid works.
